mercy = [
    'Did someone call a doctor?',
    'Right beside you.',
    'I\'ve got you.',
    'Where does it hurt?',
    'Patching you up.',
    'Let\'s get you back out there.',
    'Healing stream engaged.',
    'I\'m taking care of you.',
    'You needed a doctor?',
    'Heroes never die!',
    'I\'ll be watching over you.',
    'I\'ll enjoy the quiet while it lasts.',
    'A moment to enjoy some peace and quiet, probably just a moment though.',
    'Must violence always be the solution?',
    'Well, I suppose I\'ll be patching you up as usual.',
    'Back to square one.',
    'Now, where am I needed?',
    'The wonders of modern medicine!',
    'A clean bill of health.',
    'My prognosis is excellent.',
    'It\'s nice to be appreciated.',
    'I am touched by your support.',
    'I couldn\'t have done it alone!',
    'We all could use a helping hand sometime.',
    'Mercy on call.',
    'Pull together, we can do this.',
    'Clear!',
    'Medic!... Wait, that\'s me!',
    'Patient discharged.',
    'The prognosis is not good.',
    'You\'ve been discharged.',
    'You are not looking well.',
    'There\'s no prescription to treat what you have.',
    'I\'m no angel!',
    'Never knew I had it in me.',
    'I\'m impressed.',
    'Great job.',
    'Vital signs negative.',
    'We make a great team.',
    'We\'re unstoppable.',
    'You might not want to tell your friends about that.',
    'Say "ahh!"',
    'Regrettable, but necessary.',
    'Hello.',
    'Hello there.',
    'Greetings.',
    'I have my eye on you.',
    'Need a second opinion?',
    'I\'ll send you my consultation fee.',
    'Doctor\'s orders.',
    'How barbaric.',
    'I\'m not a miracle worker. Well... not always.',
    'On a scale of one to ten, how is your pain?',
    'Super!',
    'Take two, and call me in the morning.',
    'The doctor is in.',
    'Piece of cake.',
    'Heh. Superstition.',
    'Your guardian angel.',
    'A most impressive display.',
    'Sometimes I\'m not sure why I even bother.',
    'You really should take better care of yourself.',
    'I\'m not used to state of the art facilities these days.',
    'They used to believe that witches lived in these woods, ridiculous isn\'t it?',
    'Mercy is summoned.',
    'Heroes never die!... For a price.',
    'Mercy is here.',
    'I am the chooser of the slain.',
    'Till Valhalla!',
    'Mercy, as summoned.',
    'Mercy has been summoned.',
    'My servants never die!',
    'Casting a healing spell.',
    'My healing spell is upon you.',
    'Did someone call for a witch?',
    'Witches don\'t die that easily.',
    'I\'m on fire, but this witch doesn\'t burn.'
]